

services:
  db:
    image: mysql:8.0
    container_name: happy2be-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: happy2be
      MYSQL_USER: ${DB_USER}   # 2. Creates the app use
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    # Essential for low-memory e2-micro VMs
    command: --innodb-buffer-pool-size=64M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 5

  python-api:
      build: ./happyface  # Points to your Python Dockerfile
      ports:
        - "5001:5001"
  app:
    build: ./happy2be
    container_name: happy2be-app
    depends_on:
      db:
        condition: service_healthy
      python-api:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/happy2be?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PYTHON_API_URL: http://python-api:5001


